### PR TITLE
Update to fastify@5

### PR DESCRIPTION
**Pull request by mcollina**
This is a semver-major, it also move the minimum supported runtime to v20.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by adrai** [comment]
based on what I see it's not a major in user land... right?, theoretically there is no need to create a new version right now...?

**Review by Uzlopak — APPROVED** [review]
LGTM

**Comment by mcollina** [comment]
I'm shipping new majors for everything right now as the launch day is the 17th of September.

**Comment by adrai** [comment]
ok, we can do a major bump to be aligned, but technically, @fastify/aws-lambda v5 will be the same like v4.1.0 for the users...
Do you want me to merge and release it now?

**Review by adrai — APPROVED** [review]

**Review by gurgunday — APPROVED** [review]

**Review by zekth — APPROVED** [review]
Excellent

**Comment by mcollina** [comment]
I will ship it as the `next` tag, to be retagged when we release Fastify v5.

@adrai I can get to it if you agree.

**Comment by adrai** [comment]
> I will ship it as the `next` tag, to be retagged when we release Fastify v5.
> 
> 
> 
> @adrai I can get to it if you agree.

Agree 👍

**Comment by adrai** [comment]
v5 has just been released ;-)

**Pull request merged**
