### PR TITLE
support for event/context to decorate request

### PR DESCRIPTION
**Pull request by adrai**
This is a proposal for this nice idea: #76

### CODE REVIEW

**Comment by adrai** [comment]
if you like we can also set the default of `serializeLambdaArguments` to `false` and create a major version...
What do you think?

**Review by mcollina — APPROVED** [review]
lgtm, amazing!

**Comment by mcollina** [comment]
I think we can cut a major, yes!

**Comment by adrai** [comment]
@barticus @adworacz if this is ok for you, I will create a new major release.

**Comment by barticus** [comment]
@adrai this is amazing, thanks!

LGTM, but under the Hint in the readme the code reads like the event and context is directly set on the request, but I think by default it will be `req.awsLambda.event`, right?

**Comment by adrai** [comment]
Thank you for your feedback, v2.0.0 has just been released.

**Comment by adrai** [comment]
@mcollina do you have any idea on how to solve the problem, when someone already has a onRequest hook registered before aws-lambda-fastify registers it's hook [here](https://github.com/fastify/aws-lambda-fastify/blob/master/index.js#L10)?

Is there any possibility to register a hook at first position?

**Comment by adrai** [comment]
v2.0.1 is even better ;-)

**Comment by adworacz** [comment]
Wow thank you so much! Sorry I couldn’t respond sooner.

**Pull request merged**
