### PR TITLE
Add typescript declarations

### PR DESCRIPTION
**Pull request by kbanman**
#### Checklist

- [x ] run `npm run test` and `npm run benchmark`
- [ x] tests and/or benchmarks are included
- [ x] documentation is changed or added
- [ x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
Could you add a test for the types? We use [`tsd`](http://npm.im/tsd), check some of the other projects in the org to see how it's configured.

**Comment by adrai** [comment]
@kbanman I'm not a TypeScript user/expert... will this definition work for all usage ways?

https://github.com/fastify/aws-lambda-fastify#lambdajs

```js
exports.handler = proxy
// or
// exports.handler = (event, context, callback) => proxy(event, context, callback)
// or
// exports.handler = (event, context) => proxy(event, context)
// or
// exports.handler = async (event, context) => proxy(event, context)
```

**Comment by adrai** [comment]
@kbanman Any update on this?

**Comment by zekth** [comment]
If no update on this one i can write a PR to add tests on it

**Comment by adrai** [comment]
> If no update on this one i can write a PR to add tests on it

feel free, just make sure all signature variants work

**Pull request closed without merging**
