### PR TITLE
feat: Add TypeScript definition

### PR DESCRIPTION
**Pull request by zekth**
Following https://github.com/fastify/aws-lambda-fastify/pull/49 adding the typescript definition and tests.

Also updated the doc to document the options.

### CODE REVIEW

**Comment by adrai** [comment]
I am not a TypeScript user...
May I ask if the callback based signature is also included?

**Comment by zekth** [comment]
> I am not a TypeScript user...
> May I ask if the callback based signature is also included?

my bad, it's not. Let me fix it.

**Comment by zekth** [comment]
@fastify/typescript i'd like a confirmation on those typing if possible :)

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by adrai** [comment]
awesome weekend work 😁

released with v1.7.0

**Pull request merged**
