### PR TITLE
Update fastify to v3

### PR DESCRIPTION
**Pull request by frikille**
* Updated fastify version to v3

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by adrai** [comment]
awesome seems backwards compatible 😉

**Comment by mcollina** [comment]
There are a few breakages, but none that would matter to this module it seems!

**Comment by adrai** [comment]
Is there already some major change list?

**Comment by adrai** [comment]
found: https://github.com/fastify/fastify/blob/master/docs/Migration-Guide-V3.md

**Pull request merged**
