### PR TITLE
feat!: update to fastify@v4

### PR DESCRIPTION
**Pull request by metcoder95**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Fdawgs** [comment]
So the limitations with the shared workflow is that it only runs 'lint' and 'test' scripts, are you okay with that going forward @adrai? If not then I'd suggest keeping the current workflow.

**Review by Fdawgs — APPROVED** [review]

**Comment by mcollina** [comment]
@adrai thanks, I'm still half sick. As for the workflow... you are the lead maintainer of this, I would leave it to you.

The benefit of the shared workflow is that we can push a fix in one repo and it gets picked up everywhere.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by metcoder95** [comment]
Thanks! 🙂 

Get well soon @mcollina!

**Pull request merged**
