### PR TITLE
make sure our onRequest is always the first

### PR DESCRIPTION
**Pull request by adrai**
fixes [this](https://github.com/fastify/aws-lambda-fastify/pull/85#issuecomment-997347718)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
You can avoid the onRequest hook completely by using a getter.

**Comment by adrai** [comment]
> lgtm

so requiring the Symbols directly is ok for you? `require('fastify/lib/symbols.js')`

**Comment by adrai** [comment]
> You can avoid the onRequest hook completely by using a getter.

Can you provide more information about this? How can we access the request object in aws-lambda-fastify?

**Comment by adrai** [comment]
ok, this seems to work...
ok for you?

**Pull request merged**
